######################################################################
# Automatically generated by qmake (3.1) Sun Jun 8 14:44:58 2025
######################################################################

TEMPLATE = app
TARGET = ArchiFlow_Application
INCLUDEPATH += .

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_UP_TO=0x060000 # disables all APIs deprecated in Qt 6.0.0 and earlier

# Input
HEADERS += old_files/mainwindow.h \
           src/core/application.h \
           src/core/modulemanager.h \
           src/database/databasemanager.h \
           src/database/databaseservice.h \
           src/database/migrations.h \
           src/ui/basedialog.h \
           src/ui/mainwindow.h \
           src/ui/settingsdialog.h \
           src/ui/sidebar.h \
           src/utils/animationmanager.h \
           src/utils/documentprocessor.h \
           src/utils/environmentloader.h \
           src/utils/stylemanager.h \
           src/features/materials/aiassistantdialog.h \
           src/features/materials/aipredictiondialog.h \
           src/features/materials/groqclient.h \
           src/features/materials/materialdetailsdialog.h \
           src/features/materials/materialdialog.h \
           src/features/materials/materialmodel.h \
           src/features/materials/materialsmodule.h \
           src/features/materials/materialwidget.h \
           src/features/suppliers/supplierdialog.h \
           src/features/suppliers/suppliermodel.h \
           src/features/suppliers/suppliermodule.h \
           src/features/suppliers/supplierwidget.h \
           build/Desktop_Qt_6_9_0_MinGW_64_bit-Debug/ArchiFlow_Application_autogen/include/ui_mainwindow.h \
           /build/Desktop_Qt_6_9_0_MinGW_64_bit-Debug/ArchiFlow_Application_autogen/include/ui_mainwindow.h \
           build/Desktop_Qt_6_9_0_MinGW_64_bit-Debug/ArchiFlow_Application_autogen/PRMOGMWJPH/moc_application.cpp \
           build/Desktop_Qt_6_9_0_MinGW_64_bit-Debug/ArchiFlow_Application_autogen/PRMOGMWJPH/moc_modulemanager.cpp \
           build/Desktop_Qt_6_9_0_MinGW_64_bit-Debug/ArchiFlow_Application_autogen/M7KQ2GL7XF/moc_databasemanager.cpp \
           build/Desktop_Qt_6_9_0_MinGW_64_bit-Debug/ArchiFlow_Application_autogen/M7KQ2GL7XF/moc_databaseservice.cpp \
           build/Desktop_Qt_6_9_0_MinGW_64_bit-Debug/ArchiFlow_Application_autogen/M7KQ2GL7XF/moc_migrations.cpp \
           build/Desktop_Qt_6_9_0_MinGW_64_bit-Debug/ArchiFlow_Application_autogen/LMOUDW5VLV/moc_aiassistantdialog.cpp \
           build/Desktop_Qt_6_9_0_MinGW_64_bit-Debug/ArchiFlow_Application_autogen/LMOUDW5VLV/moc_aipredictiondialog.cpp \
           build/Desktop_Qt_6_9_0_MinGW_64_bit-Debug/ArchiFlow_Application_autogen/LMOUDW5VLV/moc_groqclient.cpp \
           build/Desktop_Qt_6_9_0_MinGW_64_bit-Debug/ArchiFlow_Application_autogen/LMOUDW5VLV/moc_materialdetailsdialog.cpp \
           build/Desktop_Qt_6_9_0_MinGW_64_bit-Debug/ArchiFlow_Application_autogen/LMOUDW5VLV/moc_materialdialog.cpp \
           build/Desktop_Qt_6_9_0_MinGW_64_bit-Debug/ArchiFlow_Application_autogen/LMOUDW5VLV/moc_materialmodel.cpp \
           build/Desktop_Qt_6_9_0_MinGW_64_bit-Debug/ArchiFlow_Application_autogen/LMOUDW5VLV/moc_materialsmodule.cpp \
           build/Desktop_Qt_6_9_0_MinGW_64_bit-Debug/ArchiFlow_Application_autogen/LMOUDW5VLV/moc_materialwidget.cpp \
           build/Desktop_Qt_6_9_0_MinGW_64_bit-Debug/ArchiFlow_Application_autogen/R54U2AQYB6/moc_supplierdialog.cpp \
           build/Desktop_Qt_6_9_0_MinGW_64_bit-Debug/ArchiFlow_Application_autogen/R54U2AQYB6/moc_suppliermodel.cpp \
           build/Desktop_Qt_6_9_0_MinGW_64_bit-Debug/ArchiFlow_Application_autogen/R54U2AQYB6/moc_suppliermodule.cpp \
           build/Desktop_Qt_6_9_0_MinGW_64_bit-Debug/ArchiFlow_Application_autogen/R54U2AQYB6/moc_supplierwidget.cpp \
           build/Desktop_Qt_6_9_0_MinGW_64_bit-Debug/ArchiFlow_Application_autogen/YPKJ5OE7LN/moc_basedialog.cpp \
           build/Desktop_Qt_6_9_0_MinGW_64_bit-Debug/ArchiFlow_Application_autogen/YPKJ5OE7LN/moc_mainwindow.cpp \
           build/Desktop_Qt_6_9_0_MinGW_64_bit-Debug/ArchiFlow_Application_autogen/YPKJ5OE7LN/moc_settingsdialog.cpp \
           build/Desktop_Qt_6_9_0_MinGW_64_bit-Debug/ArchiFlow_Application_autogen/YPKJ5OE7LN/moc_sidebar.cpp \
           build/Desktop_Qt_6_9_0_MinGW_64_bit-Debug/ArchiFlow_Application_autogen/VSCBVMNR7M/moc_animationmanager.cpp \
           build/Desktop_Qt_6_9_0_MinGW_64_bit-Debug/ArchiFlow_Application_autogen/VSCBVMNR7M/moc_stylemanager.cpp
FORMS += old_files/mainwindow.ui src/ui/mainwindow.ui
SOURCES += main.cpp \
           test_qtcharts.cpp \
           test_resources.cpp \
           /test_qtcharts.cpp \
           old_files/mainwindow.cpp \
           src/core/application.cpp \
           src/core/modulemanager.cpp \
           src/database/databasemanager.cpp \
           src/database/databaseservice.cpp \
           src/database/migrations.cpp \
           src/ui/basedialog.cpp \
           src/ui/mainwindow.cpp \
           src/ui/settingsdialog.cpp \
           src/ui/sidebar.cpp \
           src/utils/animationmanager.cpp \
           src/utils/documentprocessor.cpp \
           src/utils/environmentloader.cpp \
           src/utils/stylemanager.cpp \
           build/Desktop_Qt_6_9_0_MinGW_64_bit-Debug/ArchiFlow_Application_autogen/mocs_compilation.cpp \
           src/features/materials/aiassistantdialog.cpp \
           src/features/materials/aipredictiondialog.cpp \
           src/features/materials/groqclient.cpp \
           src/features/materials/materialdetailsdialog.cpp \
           src/features/materials/materialdialog.cpp \
           src/features/materials/materialmodel.cpp \
           src/features/materials/materialsmodule.cpp \
           src/features/materials/materialwidget.cpp \
           src/features/suppliers/supplierdialog.cpp \
           src/features/suppliers/suppliermodel.cpp \
           src/features/suppliers/suppliermodule.cpp \
           src/features/suppliers/supplierwidget.cpp \
           build/CMakeFiles/4.0.1/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           build/Desktop_Qt_6_9_0_MinGW_64_bit-Debug/.qt/rcc/qrc_app_icons.cpp \
           build/Desktop_Qt_6_9_0_MinGW_64_bit-Debug/.qt/rcc/qrc_app_resources.cpp \
           build/Desktop_Qt_6_9_0_MinGW_64_bit-Debug/CMakeFiles/3.30.5/CompilerIdCXX/CMakeCXXCompilerId.cpp
RESOURCES += resources/resources.qrc \
             build/.qt/rcc/app_icons.qrc \
             build/.qt/rcc/app_resources.qrc \
             build/Desktop_Qt_6_9_0_MinGW_64_bit-Debug/.qt/rcc/app_icons.qrc \
             build/Desktop_Qt_6_9_0_MinGW_64_bit-Debug/.qt/rcc/app_resources.qrc
